function randomChanceOfEggVoucher() {
    // Generate a random number
    const randomNumber = Math.random() * 100;
    // Return 1 if the random number is less than 7
    return randomNumber < 7 ? 1 : 0;
}

const events = {
    "Discovered a hidden berry patch": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 5 },
    "Found a shiny stone": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Uncovered an ancient ruin": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Helped a lost Pokémon find its way": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 5 },
    "Encountered a friendly traveler": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Won a playful game with wild Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 5 },
    "Found a mysterious egg": { eggVoucher: randomChanceOfEggVoucher(), balance: 0, happiness: 0 },
    "Explored a forgotten cave": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Helped rebuild a Pokémon's home": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 5 },
    "Came across an old treasure map": { eggVoucher: randomChanceOfEggVoucher(), balance: 30, happiness: 0 },
    "Discovered a hidden waterfall": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Found a lost item in the forest": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 0 },
    "Traded berries with a wandering Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Defeated a wild rival Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Collected rare flowers": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 0 },
    "Unearthed an old Pokémon toy": { eggVoucher: randomChanceOfEggVoucher(), balance: 0, happiness: 0 },
    "Participated in a Pokémon race": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 5 },
    "Helped a Pokémon cross a river": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Found a cache of berries": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Explored a new area in the forest": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Discovered a rare Pokémon habitat": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Won a game of hide and seek with wild Pokémon": {
        eggVoucher: randomChanceOfEggVoucher(),
        balance: 5,
        happiness: 0
    },
    "Found a box of ancient relics": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Helped clean up a Pokémon playground": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 0 },
    "Uncovered a buried chest": { eggVoucher: randomChanceOfEggVoucher(), balance: 30, happiness: 0 },
    "Encountered a wise old Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 5 },
    "Discovered a hidden grotto": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Won a small prize from a Pokémon contest": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Found a stash of rare candies": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Traded stories with a traveling Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Participated in a treasure hunt": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Found an old Pokémon diary": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 0 },
    "Encountered a legendary Pokémon in the wild": {
        eggVoucher: randomChanceOfEggVoucher(),
        balance: 50,
        happiness: 0
    },
    "Discovered a hidden path": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Helped a Pokémon find its lost family": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Found a rare Pokémon figurine": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Explored an abandoned mansion": { eggVoucher: randomChanceOfEggVoucher(), balance: 35, happiness: 0 },
    "Won a prize in a Pokémon skill contest": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Discovered a hidden lake": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Helped a Pokémon fix its broken home": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 5 },
    "Found a box of rare berries": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 0 },
    "Encountered a Pokémon expert": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Traded with a skilled collector": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Discovered a secret base": { eggVoucher: randomChanceOfEggVoucher(), balance: 30, happiness: 0 },
    "Helped a Pokémon retrieve its lost item": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Found a hidden cache of items": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Participated in a forest festival": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Discovered a rare Pokémon egg": { eggVoucher: randomChanceOfEggVoucher(), balance: 0, happiness: 0 },
    "Won a prize in a Pokémon race": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Found a lost treasure": { eggVoucher: randomChanceOfEggVoucher(), balance: 35, happiness: 0 },
    "Explored a mystical grove": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Helped a Pokémon in distress": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Discovered a hidden garden": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 0 },
    "Encountered a Pokémon guru": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Found an ancient Pokémon artifact": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Participated in a grand adventure": { eggVoucher: randomChanceOfEggVoucher(), balance: 30, happiness: 0 },
    "Won a special prize in a contest": { eggVoucher: randomChanceOfEggVoucher(), balance: 35, happiness: 0 },
    "Found a rare collectible item": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Discovered a secret waterfall": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Helped a Pokémon navigate a maze": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Found a chest of ancient coins": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Encountered a rare Pokémon species": { eggVoucher: randomChanceOfEggVoucher(), balance: 30, happiness: 0 },
    "Explored a legendary Pokémon's lair": { eggVoucher: randomChanceOfEggVoucher(), balance: 50, happiness: 0 },
    "Discovered a hidden gem": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Won a special award from a Pokémon guild": { eggVoucher: randomChanceOfEggVoucher(), balance: 40, happiness: 0 },
    "Found an old Pokémon scroll": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Helped a Pokémon achieve a goal": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Participated in a magical event": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Discovered a hidden beach": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Found a rare Pokémon bone": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Encountered a Pokémon sage": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Discovered a secret temple": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Helped a Pokémon retrieve an artifact": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Found a stash of rare items": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Won a prize in a Pokémon challenge": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Discovered a hidden oasis": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Explored an ancient battlefield": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Found a hidden journal": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 0 },
    "Helped a Pokémon in trouble": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Encountered a wise elder Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 5 },
    "Discovered a mysterious cavern": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Won a reward for bravery": { eggVoucher: randomChanceOfEggVoucher(), balance: 30, happiness: 0 },
    "Found an ancient fossil": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Participated in a legendary quest": { eggVoucher: randomChanceOfEggVoucher(), balance: 35, happiness: 0 },
    "Discovered a hidden valley": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Helped a Pokémon escape danger": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 5 },
    "Found a rare Pokémon feather": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 0 },
    "Encountered a legendary sage Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 30, happiness: 0 },
    "Explored a mythical forest": { eggVoucher: randomChanceOfEggVoucher(), balance: 25, happiness: 0 },
    "Discovered a hidden realm": { eggVoucher: randomChanceOfEggVoucher(), balance: 50, happiness: 0 },
    "Won a prestigious Pokémon award": { eggVoucher: randomChanceOfEggVoucher(), balance: 40, happiness: 0 },
    "Found a lost Pokémon artifact": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 0 },
    "Helped a Pokémon family": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Participated in a rare event": { eggVoucher: randomChanceOfEggVoucher(), balance: 30, happiness: 0 },
    "Discovered a hidden treasure": { eggVoucher: randomChanceOfEggVoucher(), balance: 35, happiness: 0 },
    "Explored a mystical land": { eggVoucher: randomChanceOfEggVoucher(), balance: 20, happiness: 0 },
    "Encountered a legendary guardian Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 50, happiness: 0 },
    "Saved a Pokémon from a storm": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Rescued a Pokémon from a trap": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Helped a Pokémon find its lost friend": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 5 },
    "Won a friendly battle with a wild Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 5 },
    "Helped a Pokémon recover from an injury": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Found a hidden nest with baby Pokémon": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 5 },
    "Assisted a Pokémon in learning a new move": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Protected a Pokémon from a wild predator": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 5 },
    "Helped a Pokémon build a new home": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Found a Pokémon egg and kept it safe": { eggVoucher: randomChanceOfEggVoucher(), balance: 5, happiness: 5 },
    "Assisted in a Pokémon community event": { eggVoucher: randomChanceOfEggVoucher(), balance: 10, happiness: 5 },
    "Participated in a Pokémon rescue mission": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 5 },
    "Helped a Pokémon learn to fly": { eggVoucher: randomChanceOfEggVoucher(), balance: 15, happiness: 5 },
    "Found a lost baby Pokémon and returned it to its family": {
        eggVoucher: randomChanceOfEggVoucher(),
        balance: 10,
        happiness: 5
    },
    "Protected a Pokémon from a natural disaster": {
        eggVoucher: randomChanceOfEggVoucher(),
        balance: 15,
        happiness: 5
    },

    // Negative events with eggVoucher set to 0
    "Encountered a mischievous Pokémon": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Got stuck in a thorny bush": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Lost a prized berry in the wild": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Caught in a sudden rainstorm": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Fell into a muddy pit": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Misplaced a valuable item": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Encountered a hostile wild Pokémon": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Had to navigate through a dense fog": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Tripped over a hidden root": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Got lost in a confusing maze": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Suffered from a minor injury": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Lost track of time during an adventure": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Encountered a tricky puzzle": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Had to retreat from a challenging battle": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Wasted time repairing damaged gear": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Fell for a clever trap": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Faced an unexpected challenge": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Lost a bit of courage during the adventure": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Misjudged the safety of a path": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Encountered a tricky terrain": { eggVoucher: 0, balance: 0, happiness: 0 },
    "Had to backtrack after a wrong turn": { eggVoucher: 0, balance: 0, happiness: 0 }
};

module.exports = { events };
