const { model } = require("mongoose");

events = {
    "Discovered a hidden berry patch": { eggVoucher: 0, balance: 10 },
    "Found a shiny stone": { eggVoucher: 0, balance: 25 },
    "Uncovered an ancient ruin": { eggVoucher: 1, balance: 30 },
    "Helped a lost Pokémon find its way": { eggVoucher: 0, balance: 15 },
    "Encountered a friendly traveler": { eggVoucher: 0, balance: 20 },
    "Won a playful game with wild Pokémon": { eggVoucher: 0, balance: 35 },
    "Found a mysterious egg": { eggVoucher: 1, balance: 0 },
    "Explored a forgotten cave": { eggVoucher: 1, balance: 50 },
    "Helped rebuild a Pokémon's home": { eggVoucher: 0, balance: 40 },
    "Came across an old treasure map": { eggVoucher: 1, balance: 60 },
    "Discovered a hidden waterfall": { eggVoucher: 0, balance: 25 },
    "Found a lost item in the forest": { eggVoucher: 0, balance: 10 },
    "Traded berries with a wandering Pokémon": { eggVoucher: 0, balance: 20 },
    "Defeated a wild rival Pokémon": { eggVoucher: 0, balance: 30 },
    "Collected rare flowers": { eggVoucher: 0, balance: 15 },
    "Unearthed an old Pokémon toy": { eggVoucher: 0, balance: 5 },
    "Participated in a Pokémon race": { eggVoucher: 0, balance: 40 },
    "Helped a Pokémon cross a river": { eggVoucher: 0, balance: 20 },
    "Found a cache of berries": { eggVoucher: 0, balance: 35 },
    "Explored a new area in the forest": { eggVoucher: 1, balance: 25 },
    "Discovered a rare Pokémon habitat": { eggVoucher: 1, balance: 50 },
    "Won a game of hide and seek with wild Pokémon": { eggVoucher: 0, balance: 15 },
    "Found a box of ancient relics": { eggVoucher: 1, balance: 40 },
    "Helped clean up a Pokémon playground": { eggVoucher: 0, balance: 10 },
    "Uncovered a buried chest": { eggVoucher: 1, balance: 60 },
    "Encountered a wise old Pokémon": { eggVoucher: 0, balance: 30 },
    "Discovered a hidden grotto": { eggVoucher: 1, balance: 45 },
    "Won a small prize from a Pokémon contest": { eggVoucher: 0, balance: 25 },
    "Found a stash of rare candies": { eggVoucher: 0, balance: 50 },
    "Traded stories with a traveling Pokémon": { eggVoucher: 0, balance: 20 },
    "Participated in a treasure hunt": { eggVoucher: 1, balance: 35 },
    "Found an old Pokémon diary": { eggVoucher: 0, balance: 15 },
    "Encountered a legendary Pokémon in the wild": { eggVoucher: 2, balance: 100 },
    "Discovered a hidden path": { eggVoucher: 1, balance: 30 },
    "Helped a Pokémon find its lost family": { eggVoucher: 0, balance: 20 },
    "Found a rare Pokémon figurine": { eggVoucher: 0, balance: 25 },
    "Explored an abandoned mansion": { eggVoucher: 1, balance: 70 },
    "Won a prize in a Pokémon skill contest": { eggVoucher: 0, balance: 50 },
    "Discovered a hidden lake": { eggVoucher: 1, balance: 40 },
    "Helped a Pokémon fix its broken home": { eggVoucher: 0, balance: 30 },
    "Found a box of rare berries": { eggVoucher: 0, balance: 15 },
    "Encountered a Pokémon expert": { eggVoucher: 0, balance: 25 },
    "Traded with a skilled collector": { eggVoucher: 1, balance: 50 },
    "Discovered a secret base": { eggVoucher: 1, balance: 60 },
    "Helped a Pokémon retrieve its lost item": { eggVoucher: 0, balance: 20 },
    "Found a hidden cache of items": { eggVoucher: 0, balance: 35 },
    "Participated in a forest festival": { eggVoucher: 0, balance: 40 },
    "Discovered a rare Pokémon egg": { eggVoucher: 2, balance: 0 },
    "Won a prize in a Pokémon race": { eggVoucher: 0, balance: 55 },
    "Found a lost treasure": { eggVoucher: 1, balance: 70 },
    "Explored a mystical grove": { eggVoucher: 1, balance: 30 },
    "Helped a Pokémon in distress": { eggVoucher: 0, balance: 25 },
    "Discovered a hidden garden": { eggVoucher: 0, balance: 15 },
    "Encountered a Pokémon guru": { eggVoucher: 0, balance: 20 },
    "Found an ancient Pokémon artifact": { eggVoucher: 1, balance: 50 },
    "Participated in a grand adventure": { eggVoucher: 1, balance: 60 },
    "Won a special prize in a contest": { eggVoucher: 0, balance: 75 },
    "Found a rare collectible item": { eggVoucher: 1, balance: 40 },
    "Discovered a secret waterfall": { eggVoucher: 1, balance: 35 },
    "Helped a Pokémon navigate a maze": { eggVoucher: 0, balance: 20 },
    "Found a chest of ancient coins": { eggVoucher: 0, balance: 50 },
    "Encountered a rare Pokémon species": { eggVoucher: 1, balance: 60 },
    "Explored a legendary Pokémon's lair": { eggVoucher: 2, balance: 100 },
    "Discovered a hidden gem": { eggVoucher: 1, balance: 45 },
    "Won a special award from a Pokémon guild": { eggVoucher: 0, balance: 80 },
    "Found an old Pokémon scroll": { eggVoucher: 1, balance: 30 },
    "Helped a Pokémon achieve a goal": { eggVoucher: 0, balance: 25 },
    "Participated in a magical event": { eggVoucher: 1, balance: 50 },
    "Discovered a hidden beach": { eggVoucher: 0, balance: 35 },
    "Found a rare Pokémon bone": { eggVoucher: 0, balance: 20 },
    "Encountered a Pokémon sage": { eggVoucher: 0, balance: 25 },
    "Discovered a secret temple": { eggVoucher: 1, balance: 55 },
    "Helped a Pokémon retrieve an artifact": { eggVoucher: 0, balance: 30 },
    "Found a stash of rare items": { eggVoucher: 0, balance: 45 },
    "Won a prize in a Pokémon challenge": { eggVoucher: 0, balance: 50 },
    "Discovered a hidden oasis": { eggVoucher: 1, balance: 30 },
    "Explored an ancient battlefield": { eggVoucher: 1, balance: 40 },
    "Found a hidden journal": { eggVoucher: 0, balance: 15 },
    "Helped a Pokémon escape danger": { eggVoucher: 0, balance: 25 },
    "Participated in a grand adventure quest": { eggVoucher: 1, balance: 70 },
    "Discovered a rare Pokémon footprint": { eggVoucher: 0, balance: 20 },
    "Found a hidden cave painting": { eggVoucher: 0, balance: 30 },
    "Encountered a Pokémon legend": { eggVoucher: 1, balance: 60 },
    "Won a special event prize": { eggVoucher: 0, balance: 75 },
    "Discovered a hidden sanctuary": { eggVoucher: 1, balance: 50 },
    "Helped a Pokémon solve a puzzle": { eggVoucher: 0, balance: 35 },
    "Found a cache of valuable gems": { eggVoucher: 1, balance: 60 },
    "Explored a mysterious forest": { eggVoucher: 1, balance: 40 },
    "Discovered a hidden Pokémon village": { eggVoucher: 2, balance: 100 }
};

module.exports = { events }