// add function for egg voucher chance

const events = {
    "Discovered a hidden berry patch": { eggVoucher: 0, balance: 10, happiness: 5 },
    "Found a shiny stone": { eggVoucher: 0, balance: 25, happiness: 0 },
    "Uncovered an ancient ruin": { eggVoucher: 1, balance: 30, happiness: 0 },
    "Helped a lost Pokémon find its way": { eggVoucher: 0, balance: 15, happiness: 5 },
    "Encountered a friendly traveler": { eggVoucher: 0, balance: 20, happiness: 0 },
    "Won a playful game with wild Pokémon": { eggVoucher: 0, balance: 35, happiness: 5 },
    "Found a mysterious egg": { eggVoucher: 1, balance: 0, happiness: 0 },
    "Explored a forgotten cave": { eggVoucher: 1, balance: 50, happiness: 0 },
    "Helped rebuild a Pokémon's home": { eggVoucher: 0, balance: 40, happiness: 5 },
    "Came across an old treasure map": { eggVoucher: 1, balance: 60, happiness: 0 },
    "Discovered a hidden waterfall": { eggVoucher: 0, balance: 25, happiness: 0 },
    "Found a lost item in the forest": { eggVoucher: 0, balance: 10, happiness: 0 },
    "Traded berries with a wandering Pokémon": { eggVoucher: 0, balance: 20, happiness: 0 },
    "Defeated a wild rival Pokémon": { eggVoucher: 0, balance: 30, happiness: 0 },
    "Collected rare flowers": { eggVoucher: 0, balance: 15, happiness: 0 },
    "Unearthed an old Pokémon toy": { eggVoucher: 0, balance: 5, happiness: 0 },
    "Participated in a Pokémon race": { eggVoucher: 0, balance: 40, happiness: 5 },
    "Helped a Pokémon cross a river": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Found a cache of berries": { eggVoucher: 0, balance: 35, happiness: 0 },
    "Explored a new area in the forest": { eggVoucher: 1, balance: 25, happiness: 0 },
    "Discovered a rare Pokémon habitat": { eggVoucher: 1, balance: 50, happiness: 0 },
    "Won a game of hide and seek with wild Pokémon": { eggVoucher: 0, balance: 15, happiness: 0 },
    "Found a box of ancient relics": { eggVoucher: 1, balance: 40, happiness: 0 },
    "Helped clean up a Pokémon playground": { eggVoucher: 0, balance: 10, happiness: 0 },
    "Uncovered a buried chest": { eggVoucher: 1, balance: 60, happiness: 0 },
    "Encountered a wise old Pokémon": { eggVoucher: 0, balance: 30, happiness: 5 },
    "Discovered a hidden grotto": { eggVoucher: 1, balance: 45, happiness: 0 },
    "Won a small prize from a Pokémon contest": { eggVoucher: 0, balance: 25, happiness: 0 },
    "Found a stash of rare candies": { eggVoucher: 0, balance: 50, happiness: 0 },
    "Traded stories with a traveling Pokémon": { eggVoucher: 0, balance: 20, happiness: 0 },
    "Participated in a treasure hunt": { eggVoucher: 1, balance: 35, happiness: 0 },
    "Found an old Pokémon diary": { eggVoucher: 0, balance: 15, happiness: 0 },
    "Encountered a legendary Pokémon in the wild": { eggVoucher: 2, balance: 100, happiness: 0 },
    "Discovered a hidden path": { eggVoucher: 1, balance: 30, happiness: 0 },
    "Helped a Pokémon find its lost family": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Found a rare Pokémon figurine": { eggVoucher: 0, balance: 25, happiness: 0 },
    "Explored an abandoned mansion": { eggVoucher: 1, balance: 70, happiness: 0 },
    "Won a prize in a Pokémon skill contest": { eggVoucher: 0, balance: 50, happiness: 0 },
    "Discovered a hidden lake": { eggVoucher: 1, balance: 40, happiness: 0 },
    "Helped a Pokémon fix its broken home": { eggVoucher: 0, balance: 30, happiness: 5 },
    "Found a box of rare berries": { eggVoucher: 0, balance: 15, happiness: 0 },
    "Encountered a Pokémon expert": { eggVoucher: 0, balance: 25, happiness: 0 },
    "Traded with a skilled collector": { eggVoucher: 1, balance: 50, happiness: 0 },
    "Discovered a secret base": { eggVoucher: 1, balance: 60, happiness: 0 },
    "Helped a Pokémon retrieve its lost item": { eggVoucher: 0, balance: 20, happiness: 0 },
    "Found a hidden cache of items": { eggVoucher: 0, balance: 35, happiness: 0 },
    "Participated in a forest festival": { eggVoucher: 0, balance: 40, happiness: 0 },
    "Discovered a rare Pokémon egg": { eggVoucher: 2, balance: 0, happiness: 0 },
    "Won a prize in a Pokémon race": { eggVoucher: 0, balance: 55, happiness: 0 },
    "Found a lost treasure": { eggVoucher: 1, balance: 70, happiness: 0 },
    "Explored a mystical grove": { eggVoucher: 1, balance: 30, happiness: 0 },
    "Helped a Pokémon in distress": { eggVoucher: 0, balance: 25, happiness: 5 },
    "Discovered a hidden garden": { eggVoucher: 0, balance: 15, happiness: 0 },
    "Encountered a Pokémon guru": { eggVoucher: 0, balance: 20, happiness: 0 },
    "Found an ancient Pokémon artifact": { eggVoucher: 1, balance: 50, happiness: 0 },
    "Participated in a grand adventure": { eggVoucher: 1, balance: 60, happiness: 0 },
    "Won a special prize in a contest": { eggVoucher: 0, balance: 75, happiness: 0 },
    "Found a rare collectible item": { eggVoucher: 1, balance: 40, happiness: 0 },
    "Discovered a secret waterfall": { eggVoucher: 1, balance: 35, happiness: 0 },
    "Helped a Pokémon navigate a maze": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Found a chest of ancient coins": { eggVoucher: 0, balance: 50, happiness: 0 },
    "Encountered a rare Pokémon species": { eggVoucher: 1, balance: 60, happiness: 0 },
    "Explored a legendary Pokémon's lair": { eggVoucher: 2, balance: 100, happiness: 0 },
    "Discovered a hidden gem": { eggVoucher: 1, balance: 45, happiness: 0 },
    "Won a special award from a Pokémon guild": { eggVoucher: 0, balance: 80, happiness: 0 },
    "Found an old Pokémon scroll": { eggVoucher: 1, balance: 30, happiness: 0 },
    "Helped a Pokémon achieve a goal": { eggVoucher: 0, balance: 25, happiness: 5 },
    "Participated in a magical event": { eggVoucher: 1, balance: 50, happiness: 0 },
    "Discovered a hidden beach": { eggVoucher: 0, balance: 35, happiness: 0 },
    "Found a rare Pokémon bone": { eggVoucher: 0, balance: 20, happiness: 0 },
    "Encountered a Pokémon sage": { eggVoucher: 0, balance: 25, happiness: 0 },
    "Discovered a secret temple": { eggVoucher: 1, balance: 55, happiness: 0 },
    "Helped a Pokémon retrieve an artifact": { eggVoucher: 0, balance: 30, happiness: 0 },
    "Found a stash of rare items": { eggVoucher: 0, balance: 45, happiness: 0 },
    "Won a prize in a Pokémon challenge": { eggVoucher: 0, balance: 50, happiness: 0 },
    "Discovered a hidden oasis": { eggVoucher: 1, balance: 30, happiness: 0 },
    "Explored an ancient battlefield": { eggVoucher: 1, balance: 40, happiness: 0 },
    "Found a hidden journal": { eggVoucher: 0, balance: 15, happiness: 0 },
    "Helped a Pokémon in trouble": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Encountered a wise elder Pokémon": { eggVoucher: 0, balance: 35, happiness: 5 },
    "Discovered a mysterious cavern": { eggVoucher: 1, balance: 50, happiness: 0 },
    "Won a reward for bravery": { eggVoucher: 0, balance: 60, happiness: 0 },
    "Found an ancient fossil": { eggVoucher: 1, balance: 40, happiness: 0 },
    "Participated in a legendary quest": { eggVoucher: 2, balance: 75, happiness: 0 },
    "Discovered a hidden valley": { eggVoucher: 1, balance: 45, happiness: 0 },
    "Helped a Pokémon escape danger": { eggVoucher: 0, balance: 30, happiness: 5 },
    "Found a rare Pokémon feather": { eggVoucher: 0, balance: 25, happiness: 0 },
    "Encountered a legendary sage Pokémon": { eggVoucher: 1, balance: 60, happiness: 0 },
    "Explored a mythical forest": { eggVoucher: 1, balance: 50, happiness: 0 },
    "Discovered a hidden realm": { eggVoucher: 2, balance: 100, happiness: 0 },
    "Won a prestigious Pokémon award": { eggVoucher: 0, balance: 85, happiness: 0 },
    "Found a lost Pokémon artifact": { eggVoucher: 1, balance: 35, happiness: 0 },
    "Helped a Pokémon family": { eggVoucher: 0, balance: 25, happiness: 5 },
    "Participated in a rare event": { eggVoucher: 1, balance: 60, happiness: 0 },
    "Discovered a hidden treasure": { eggVoucher: 1, balance: 70, happiness: 0 },
    "Explored a mystical land": { eggVoucher: 1, balance: 40, happiness: 0 },
    "Encountered a legendary guardian Pokémon": { eggVoucher: 2, balance: 100, happiness: 0 },
    "Saved a Pokémon from a storm": { eggVoucher: 0, balance: 25, happiness: 5 },
    "Rescued a Pokémon from a trap": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Helped a Pokémon find its lost friend": { eggVoucher: 0, balance: 15, happiness: 5 },
    "Won a friendly battle with a wild Pokémon": { eggVoucher: 0, balance: 30, happiness: 5 },
    "Helped a Pokémon recover from an injury": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Found a hidden nest with baby Pokémon": { eggVoucher: 0, balance: 15, happiness: 5 },
    "Assisted a Pokémon in learning a new move": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Protected a Pokémon from a wild predator": { eggVoucher: 0, balance: 25, happiness: 5 },
    "Helped a Pokémon build a new home": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Found a Pokémon egg and kept it safe": { eggVoucher: 0, balance: 15, happiness: 5 },
    "Assisted in a Pokémon community event": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Participated in a Pokémon rescue mission": { eggVoucher: 0, balance: 30, happiness: 5 },
    "Helped a Pokémon learn to fly": { eggVoucher: 0, balance: 25, happiness: 5 },
    "Found a lost baby Pokémon and returned it to its family": { eggVoucher: 0, balance: 20, happiness: 5 },
    "Protected a Pokémon from a natural disaster": { eggVoucher: 0, balance: 30, happiness: 5 }
};


module.exports = { events }